import { useEffect,useMemo,useRef,useState } from 'react';
import { WineForm } from '../wines/WineForm';
import type { WineInput } from '../../lib/db/schema';
import type { RecognitionResult } from '../recognition/schema';
import { authHeaders } from '../../lib/auth/client';
import { extractPhotoMetadata,type PhotoMetadata } from './photoMetadata';
import { prepareRecognitionImage } from './prepareImage';
import { batchImageUrl,confirmBatchWine,createBatchSession,getBatchSession,listBatchSessions,rejectBatchWine,stageBatchWine,submitBatchSession,type BatchRecognitionItem,type BatchRecognitionSession } from './batchApi';
import '../../batchScan.css';

type PreparedPhoto={original:File;recognition:File;metadata:PhotoMetadata;width:number;height:number;preview:string};
type DraftWine={key:string;photos:PreparedPhoto[];preparing:boolean;error:string};
const emptyWine=():DraftWine=>({key:crypto.randomUUID(),photos:[],preparing:false,error:''});
function suggestedTags(result:RecognitionResult){const seen=new Set<string>();return [result.country,result.region,result.appellation,...result.grapes,result.style].filter((x):x is string=>Boolean(x)).map(x=>x.trim()).filter(x=>{const k=x.toLowerCase();if(!x||seen.has(k))return false;seen.add(k);return true}).slice(0,8)}
function recognitionInitial(r:RecognitionResult):Partial<WineInput>{return {producer:r.producer??'',wineName:r.wineName??'',vintage:r.vintage,country:r.country,region:r.region,appellation:r.appellation,grapes:r.grapes,grapeBlend:r.grapeBlend,wineStyle:r.style,alcoholPercentage:r.alcoholPercentage,tastingDate:r.tastingDate,locationName:r.locationName,latitude:r.latitude,longitude:r.longitude,tags:suggestedTags(r),recognitionConfidence:r.confidence,recognitionStatus:'review'}}

function BatchImage({id,alt}:{id:string;alt:string}){const [src,setSrc]=useState('');useEffect(()=>{let active=true,url='';fetch(batchImageUrl(id),{headers:authHeaders()}).then(r=>{if(!r.ok)throw new Error('image');return r.blob()}).then(blob=>{if(active){url=URL.createObjectURL(blob);setSrc(url)}}).catch(()=>undefined);return()=>{active=false;if(url)URL.revokeObjectURL(url)}},[id]);return src?<img src={src} alt={alt}/>:<div className="batch-image-placeholder">Wine</div>}

export function BatchScanPage(){
  const [drafts,setDrafts]=useState<DraftWine[]>([emptyWine(),emptyWine()]),[session,setSession]=useState<BatchRecognitionSession|null>(null),[submitting,setSubmitting]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[reviewId,setReviewId]=useState<string|null>(null),[history,setHistory]=useState<Array<{id:string;status:string;totalItems:number;confirmedItems:number;updatedAt:string}>>([]);
  const poll=useRef<number|undefined>(undefined);
  const populated=drafts.filter(x=>x.photos.length),readyToSubmit=populated.length>=2&&!drafts.some(x=>x.preparing||x.error);
  const reviewItem=session?.items.find(x=>x.id===reviewId)??null;
  const readyItems=useMemo(()=>session?.items.filter(x=>x.status==='ready')??[],[session]);
  function stopPoll(){if(poll.current)window.clearInterval(poll.current);poll.current=undefined}
  async function refreshSession(id:string){const next=await getBatchSession(id);setSession(next);if(['queued','running'].includes(next.status)&&!poll.current)poll.current=window.setInterval(()=>void refreshSession(id).catch(()=>undefined),10000);if(!['queued','running'].includes(next.status))stopPoll();return next}
  useEffect(()=>{let active=true;listBatchSessions().then(async result=>{if(!active)return;setHistory(result.items);const resumable=result.items.find(x=>['queued','running','ready','partial'].includes(x.status));if(resumable)await refreshSession(resumable.id)}).catch(()=>undefined);return()=>{active=false;stopPoll()}},[]);

  async function choose(index:number,files:File[]){if(!files.length)return;setError('');setDrafts(xs=>xs.map((x,i)=>i===index?{...x,preparing:true,error:''}:x));try{const prepared=await Promise.all(files.map(async file=>{const [metadata,image]=await Promise.all([extractPhotoMetadata(file),prepareRecognitionImage(file,1600,0.80)]);return {original:file,recognition:image.file,metadata,width:image.width,height:image.height,preview:URL.createObjectURL(file)}}));setDrafts(xs=>xs.map((x,i)=>i===index?{...x,photos:prepared,preparing:false,error:''}:x))}catch(e){setDrafts(xs=>xs.map((x,i)=>i===index?{...x,preparing:false,error:(e as Error).message}:x))}}
  function removeDraft(index:number){setDrafts(xs=>xs.length<=2?xs.map((x,i)=>i===index?emptyWine():x):xs.filter((_,i)=>i!==index))}

  async function submit(){if(!readyToSubmit)return;setSubmitting(true);setError('');setNotice('');try{const created=await createBatchSession();for(let i=0;i<populated.length;i++){const wine=populated[i];await stageBatchWine(created.id,i,wine.photos)}await submitBatchSession(created.id);setNotice(`${populated.length} wines queued with Gemini Batch API. You can close WineLog; recognition continues in the background.`);await refreshSession(created.id);setHistory((await listBatchSessions()).items)}catch(e){setError((e as Error).message)}finally{setSubmitting(false)}}
  async function discard(item:BatchRecognitionItem){if(!session||!confirm('Discard this pending identification and its staged photos?'))return;await rejectBatchWine(session.id,item.id);setReviewId(null);await refreshSession(session.id)}
  async function afterSaved(){if(!session)return;setReviewId(null);const next=await refreshSession(session.id),nextReady=next.items.find(x=>x.status==='ready');if(nextReady)setReviewId(nextReady.id);setNotice('Wine confirmed and saved. Staged recognition copy deleted; the original photo is now attached to the wine.')}

  if(session)return <section className="batch-scan-page"><div className="hero compact"><p className="eyebrow">BATCH SCAN</p><h1>{session.totalItems} wines in this batch.</h1><p>{session.status==='queued'||session.status==='running'?'Gemini is processing these independent wine requests in the background. You can close WineLog safely.':`${readyItems.length} ready for review · ${session.confirmedItems} confirmed.`}</p></div>
    <div className={`batch-session-status ${session.status}`}><strong>{session.status.toUpperCase()}</strong><span>Batch {session.id.slice(0,8)} · expires {new Date(session.expiresAt).toLocaleDateString()}</span></div>{notice&&<p className="producer-notice">{notice}</p>}{error&&<p className="scan-error">{error}</p>}
    <div className="batch-result-grid">{session.items.map((item,index)=><article className={`batch-result-card ${item.status}`} key={item.id}>{item.imageIds[0]?<BatchImage id={item.imageIds[0]} alt={`Wine ${index+1}`}/>:<div className="batch-image-placeholder">Wine {index+1}</div>}<div><span className="batch-item-state">{item.status}</span><h2>{item.recognition?.wineName||`Wine ${index+1}`}</h2><p>{item.recognition?.producer||item.error||'Waiting for recognition'}</p>{item.recognition?.vintage&&<small>{item.recognition.vintage} · {Math.round((item.recognition.confidence??0)*100)}% confidence</small>}{item.status==='ready'&&<button type="button" onClick={()=>setReviewId(item.id)}>Review & save</button>}{item.status==='failed'&&<button type="button" className="secondary-danger" onClick={()=>void discard(item)}>Discard</button>}{item.status==='confirmed'&&item.confirmedWineId&&<a href={`/wines/${item.confirmedWineId}`}>View saved wine</a>}</div></article>)}</div>
    {reviewItem?.recognition&&<div className="batch-review"><div className="batch-review-heading"><div><p className="eyebrow">REVIEW IDENTIFICATION</p><h2>{reviewItem.recognition.wineName||'Review wine'}</h2></div><button type="button" onClick={()=>setReviewId(null)}>Close</button></div><div className="batch-review-images">{reviewItem.imageIds.map((id,i)=><BatchImage key={id} id={id} alt={`Label ${i+1}`}/>)}</div><WineForm initial={recognitionInitial(reviewItem.recognition)} onSave={wine=>confirmBatchWine(session.id,reviewItem.id,wine)} onSaved={()=>void afterSaved()} submitLabel="Confirm & save wine"/><button type="button" className="secondary-danger batch-discard" onClick={()=>void discard(reviewItem)}>Discard this identification</button></div>}
    <div className="batch-footer-actions"><button type="button" onClick={()=>{stopPoll();setSession(null);setReviewId(null);setDrafts([emptyWine(),emptyWine()]);setNotice('')}}>Start another batch</button></div>
  </section>;

  return <section className="batch-scan-page"><div className="hero compact"><p className="eyebrow">BATCH SCAN</p><h1>Scan several wines for less.</h1><p>Each section is one bottle. Add front, back, neck or other labels inside that bottle’s section. WineLog sends each bottle as an independent Gemini Batch request, while keeping all of its labels together.</p></div>{error&&<p className="scan-error">{error}</p>}
    <div className="batch-draft-list">{drafts.map((wine,index)=><section className="batch-draft" key={wine.key}><div className="batch-draft-title"><div><span>WINE {index+1}</span><strong>{wine.photos.length?`${wine.photos.length} label photo${wine.photos.length===1?'':'s'}`:'Add this bottle’s labels'}</strong></div><button type="button" onClick={()=>removeDraft(index)}>Remove</button></div>{wine.photos.length?<div className="batch-draft-photos">{wine.photos.map(photo=><img src={photo.preview} alt={`Wine ${index+1} label`} key={photo.preview}/>)}</div>:<div className="batch-empty-photo">Front · back · neck · additional labels</div>}<label className="batch-photo-picker">{wine.preparing?'Preparing recognition copies…':wine.photos.length?'Replace photos':'Choose photos'}<input className="visually-hidden" type="file" accept="image/*" multiple disabled={wine.preparing||submitting} onChange={e=>void choose(index,Array.from(e.target.files??[]))}/></label>{wine.error&&<small className="scan-error">{wine.error}</small>}{wine.photos.length>0&&<small>{(wine.photos.reduce((s,p)=>s+p.recognition.size,0)/1024/1024).toFixed(1)} MB prepared for recognition · originals kept separately for final save</small>}</section>)}</div>
    <button type="button" className="batch-add-wine" onClick={()=>setDrafts(xs=>[...xs,emptyWine()])}>＋ Add another wine</button><div className="batch-submit-panel"><p>Batch Scan uses 1600px JPEG recognition copies at 80% quality. WineLog automatically splits the Gemini payload before it approaches the 20 MB inline Batch API limit.</p><button type="button" className="wide-action" disabled={!readyToSubmit||submitting} onClick={()=>void submit()}>{submitting?'Uploading & queueing…':`Identify ${populated.length||0} wines in batch`}</button></div>
    {history.length>0&&<section className="batch-history"><h2>Recent batches</h2>{history.slice(0,5).map(h=><button key={h.id} type="button" onClick={()=>void refreshSession(h.id)}><span>{new Date(h.updatedAt).toLocaleString()}</span><strong>{h.totalItems} wines · {h.status}</strong><small>{h.confirmedItems} confirmed</small></button>)}</section>}
  </section>
}
