import { useEffect,useState } from 'react';
import { apiJson } from '../../lib/auth/api';
type Member={id:string;display_name:string;email:string;status:string;balance:number;reserved:number};
type MemberUsageKind={kind:string;requests:number;searchQueries:number;units:number;estimatedMarginalUsd:number};
type MemberUsage={userId:string;requests:number;searchQueries:number;promptTokens:number;outputTokens:number;smartSearchRequests:number;smartSearchUnits:number;estimatedMarginalUsd:number;kinds:MemberUsageKind[]};
type Overview={members:Member[];actions:string[];settings:Record<string,unknown>|null;prices:Array<{id:string;action:string;credits:number}>;aiCost:{month:string;usd:number;searches:number};memberUsage:{month:string;items:MemberUsage[]};storage:Array<{owner_id:string;byte_size:number}>;reviewOperations:Array<{id:string;user_id:string;path:string}>};
type RolloutState='not_started'|'paused'|'running'|'complete';
type RolloutStatus={storage:{state:RolloutState;objects:number;error:string|null};research:{state:RolloutState;wines:{processed:number;total:number};producers:{processed:number;total:number};error:string|null}};
const defaults={memberLimit:25,memberStorageBytes:100*1024*1024,totalStorageBytes:8*1024*1024*1024,aiConcurrency:2,aiDailyOperations:100,aiDailyEmbeddingRequests:400,aiMonthlyBudgetUsd:0,aiUnitBudgetUsd:1,cloudflareWarningUsd:0,cloudflareStopUsd:0,cloudflareObservedUsd:0,cloudflareObservedMonth:new Date().toISOString().slice(0,7),allowOverages:true};
const budgetLabels:Record<string,string>={memberLimit:'Member limit',memberStorageBytes:'Storage per member (bytes)',totalStorageBytes:'Total storage (bytes)',aiConcurrency:'Simultaneous AI actions',aiDailyOperations:'AI actions per day',aiDailyEmbeddingRequests:'Smart Search embeddings per account per day',aiMonthlyBudgetUsd:'Monthly AI budget (US$)',aiUnitBudgetUsd:'Estimated hold per unit, including retries (US$)',cloudflareWarningUsd:'Cloudflare warning amount (US$)',cloudflareStopUsd:'Cloudflare stop amount (US$)',cloudflareObservedUsd:'Measured Cloudflare cost this month (US$)',cloudflareObservedMonth:'Measurement month (YYYY-MM)',allowOverages:'Allow paid Cloudflare usage below the hard stop'};
const formatBytes=(bytes:number)=>{if(!Number.isFinite(bytes)||bytes<=0)return '0 B';const units=['B','KB','MB','GB','TB'];let value=bytes,index=0;while(value>=1024&&index<units.length-1){value/=1024;index++}return `${value<10&&index>0?value.toFixed(1):Math.round(value)} ${units[index]}`};
const labelKind=(kind:string)=>kind.replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase());
const stateLabel=(state:RolloutState)=>state==='not_started'?'Not started':state==='paused'?'Paused':state==='running'?'Running in background':'Complete';
const utcBudgetWindow=()=>{const now=new Date(),current=now.toISOString().slice(0,7),nextDate=new Date(Date.UTC(now.getUTCFullYear(),now.getUTCMonth()+1,1)),days=Math.ceil((nextDate.getTime()-now.getTime())/86_400_000);return {current,next:nextDate.toISOString().slice(0,7),days}};
export function AdminPage(){
 const [data,setData]=useState<Overview|null>(null),[config,setConfig]=useState<Record<string,unknown>>(defaults),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[rolloutStatus,setRolloutStatus]=useState<RolloutStatus|null>(null);
 const [userId,setUserId]=useState(''),[credits,setCredits]=useState(1),[action,setAction]=useState('scan_single'),[email,setEmail]=useState('');
 const rolloutRunning=rolloutStatus?.storage.state==='running'||rolloutStatus?.research.state==='running';
 async function load(){const [next,rollout]=await Promise.all([apiJson<Overview>('/api/admin/overview'),apiJson<RolloutStatus>('/api/admin/rollout/status')]);setData(next);setRolloutStatus(rollout);if(next.settings)setConfig(next.settings)}
 useEffect(()=>{void load().catch(e=>setMessage(e.message))},[]);
 useEffect(()=>{if(!data||window.location.hash!=='#member-usage')return;const frame=window.requestAnimationFrame(()=>document.getElementById('member-usage')?.scrollIntoView({block:'start'}));return()=>window.cancelAnimationFrame(frame)},[data]);
 useEffect(()=>{if(!rolloutRunning)return;const timer=window.setInterval(()=>{void apiJson<RolloutStatus>('/api/admin/rollout/status').then(setRolloutStatus).catch(()=>undefined)},5000);return()=>window.clearInterval(timer)},[rolloutRunning]);
 async function run(fn:()=>Promise<unknown>){setBusy(true);setMessage('');try{const result=await fn();setMessage(typeof result==='string'?result:'Saved');await load()}catch(e){setMessage((e as Error).message)}finally{setBusy(false)}}
 async function startRollout(kind:'storage'|'research'){
  const result=await apiJson<{accepted:boolean;alreadyComplete?:boolean;status:RolloutStatus}>(`/api/admin/rollout/${kind}`,'POST',{});setRolloutStatus(result.status);
  if(result.alreadyComplete)return `${kind==='storage'?'R2 storage inventory':'Research index'} is already complete.`;
  return `${kind==='storage'?'R2 storage inventory':'Research indexing'} is running in the background. You can leave this page.`;
 }
 const usageByUser=new Map(data?.memberUsage.items.map(item=>[item.userId,item])??[]),storageByUser=new Map(data?.storage.map(item=>[item.owner_id,Number(item.byte_size)||0])??[]);
 const budgetWindow=utcBudgetWindow(),observedMonth=String(config.cloudflareObservedMonth??'');
 const researchProcessed=(rolloutStatus?.research.wines.processed??0)+(rolloutStatus?.research.producers.processed??0),researchTotal=(rolloutStatus?.research.wines.total??0)+(rolloutStatus?.research.producers.total??0);
 return <section className="account-page"><h1>Owner controls</h1>{message&&<p role="status">{message}</p>}{data&&<p>Estimated provider AI cost: US${data.aiCost.usd.toFixed(2)} · {data.aiCost.searches} searches. Estimates can lag provider billing.</p>}
 {observedMonth!==budgetWindow.current&&<p role="alert"><strong>AI is paused for the new month.</strong> In Pilot budgets, set Measurement month to <strong>{budgetWindow.current}</strong>, enter this month’s measured Cloudflare cost (usually 0 at the start of a month), then press Save budgets.</p>}
 {observedMonth===budgetWindow.current&&budgetWindow.days<=3&&<p role="status"><strong>Monthly AI budget check due soon.</strong> At 00:00 UTC on {budgetWindow.next}-01, WineLog will pause credit-gated AI until Measurement month is changed to <strong>{budgetWindow.next}</strong> and the new month’s measured Cloudflare cost is saved.</p>}
 {Number(config.cloudflareObservedUsd)>=Number(config.cloudflareWarningUsd)&&Number(config.cloudflareWarningUsd)>0&&<p role='alert'>Cloudflare spending has reached your warning amount. Review current usage before more AI work.</p>}
 {data&&<section id="member-usage" className="member-usage" aria-labelledby="member-usage-title">
  <h2 id="member-usage-title">Member usage · {data.memberUsage.month}</h2>
  <p>Current-month activity is attributed to the account that caused it. Marginal cost uses list pricing before the deployment-wide free grounding allowance; use the total above for provider-bill reconciliation.</p>
  <div className="member-usage-grid">{data.members.map(member=>{const usage=usageByUser.get(member.id),storage=storageByUser.get(member.id)??0;return <article className="member-usage-card" key={member.id}>
   <header><strong>{member.display_name}</strong><small>{member.email} · {member.status}</small></header>
   <dl><div><dt>AI requests</dt><dd>{usage?.requests??0}</dd></div><div><dt>Grounding searches</dt><dd>{usage?.searchQueries??0}</dd></div><div><dt>Smart Search</dt><dd>{usage?.smartSearchRequests??0} requests</dd></div><div><dt>Wines embedded</dt><dd>{usage?.smartSearchUnits??0}</dd></div><div><dt>Est. marginal AI</dt><dd>US${(usage?.estimatedMarginalUsd??0).toFixed(3)}</dd></div><div><dt>Storage</dt><dd>{formatBytes(storage)}</dd></div><div><dt>Wallet</dt><dd>{member.balance} credits</dd></div><div><dt>Reserved</dt><dd>{member.reserved} credits</dd></div></dl>
   {!!usage?.kinds.length&&<details><summary>Feature breakdown</summary><ul>{usage.kinds.map(kind=><li key={kind.kind}><span>{labelKind(kind.kind)}</span><span>{kind.requests} req · {kind.searchQueries} searches · US${kind.estimatedMarginalUsd.toFixed(3)}</span></li>)}</ul></details>}
  </article>})}</div>
  <p className="usage-note">Smart Search embeddings remain zero-credit. Their requests and indexed-wine counts are still tracked even when a provider does not expose enough billing metadata to estimate an exact embedding cost.</p>
 </section>}
 <fieldset disabled={busy}><legend>Pilot budgets</legend><p>Set your budget amounts before admitting members. Storage is in bytes and budgets are in US dollars.</p>{Object.entries(config).map(([key,value])=><label key={key}>{budgetLabels[key]??key}{typeof value==='boolean'?<input type="checkbox" checked={value} onChange={e=>setConfig({...config,[key]:e.target.checked})}/>:<input type={typeof value==='number'?'number':'text'} value={String(value)} onChange={e=>setConfig({...config,[key]:typeof value==='number'?Number(e.target.value):e.target.value})}/>}</label>)}<button onClick={()=>void run(()=>apiJson('/api/admin/settings','PUT',config))}>Save budgets</button></fieldset>
 <fieldset disabled={busy}><legend>Credit prices</legend><select aria-label="AI action" value={action} onChange={e=>setAction(e.target.value)}>{data?.actions.map(a=><option key={a} value={a}>{a.replaceAll('_',' ')}</option>)}</select><label>Credits<input type="number" min="1" value={credits} onChange={e=>setCredits(Number(e.target.value))}/></label><button onClick={()=>void run(()=>apiJson('/api/admin/prices','POST',{action,credits}))}>Set new price</button><ul>{data?.prices.slice(0,10).map(p=><li key={p.id}>{p.action}: {p.credits}</li>)}</ul></fieldset>
 <fieldset disabled={busy}><legend>Members and grants</legend><select aria-label="Member" value={userId} onChange={e=>setUserId(e.target.value)}><option value="">Choose member</option>{data?.members.map(m=><option key={m.id} value={m.id}>{m.display_name} ({m.balance} credits)</option>)}</select><label>Credits to grant<input type="number" min="1" value={credits} onChange={e=>setCredits(Number(e.target.value))}/></label><button disabled={!userId} onClick={()=>void run(()=>apiJson('/api/admin/credits/grant','POST',{userId,credits,idempotencyKey:crypto.randomUUID(),reason:'Owner grant'}))}>Grant credits</button><ul>{data?.members.filter(m=>m.id!=='owner').map(m=><li key={m.id}>{m.email} — {m.status} <button onClick={()=>void run(()=>apiJson(`/api/admin/members/${m.id}`,'PATCH',{status:m.status==='active'?'suspended':'active'}))}>{m.status==='active'?'Suspend':'Restore'}</button></li>)}</ul></fieldset>
 <fieldset disabled={busy}><legend>Launch preparation</legend>
  <p>These one-time jobs now run in the background. It is safe to leave this page after starting them; progress is saved and resumes automatically.</p>
  {rolloutStatus&&<div>
   <p><strong>R2 storage:</strong> {stateLabel(rolloutStatus.storage.state)} · {rolloutStatus.storage.objects} objects tracked.</p>
   {rolloutStatus.storage.error&&<p role="alert">Last storage inventory error: {rolloutStatus.storage.error}</p>}
   <button disabled={rolloutStatus.storage.state==='complete'||rolloutStatus.storage.state==='running'} onClick={()=>void run(()=>startRollout('storage'))}>{rolloutStatus.storage.state==='complete'?'R2 inventory complete':rolloutStatus.storage.state==='paused'?'Resume R2 inventory':'Inventory R2 storage'}</button>
   <p><strong>Existing research:</strong> {stateLabel(rolloutStatus.research.state)} · wines {rolloutStatus.research.wines.processed}/{rolloutStatus.research.wines.total} · producers {rolloutStatus.research.producers.processed}/{rolloutStatus.research.producers.total}.</p>
   {researchTotal>0&&<progress max={researchTotal} value={Math.min(researchProcessed,researchTotal)} aria-label="Research indexing progress"/>}
   {rolloutStatus.research.error&&<p role="alert">Last research indexing error: {rolloutStatus.research.error}</p>}
   <button disabled={rolloutStatus.research.state==='complete'||rolloutStatus.research.state==='running'} onClick={()=>void run(()=>startRollout('research'))}>{rolloutStatus.research.state==='complete'?'Research index complete':rolloutStatus.research.state==='paused'?'Resume research indexing':'Index existing research'}</button>
  </div>}
  <label>Invite email<input type="email" value={email} onChange={e=>setEmail(e.target.value)}/></label><button onClick={()=>void run(async()=>(await apiJson<{url:string}>('/api/admin/invitations','POST',{email})).url)}>Create member invitation</button>
 </fieldset>
 {!!data?.reviewOperations.length&&<><h2>Operations needing reconciliation</h2><p>These reservations remain held because completion is uncertain. Reconcile provider status before releasing credits.</p><ul>{data.reviewOperations.map(op=><li key={op.id}>{op.id} — {op.path}</li>)}</ul></>}
 </section>;
}
