import { useEffect,useState } from 'react';
import { apiJson } from '../../lib/auth/api';
type Overview={members:Array<{id:string;display_name:string;email:string;status:string;balance:number;reserved:number}>;actions:string[];settings:Record<string,unknown>|null;prices:Array<{id:string;action:string;credits:number}>;aiCost:{usd:number;searches:number};storage:Array<{owner_id:string;byte_size:number}>;reviewOperations:Array<{id:string;user_id:string;path:string}>};
const defaults={memberLimit:25,memberStorageBytes:100*1024*1024,totalStorageBytes:8*1024*1024*1024,aiConcurrency:2,aiDailyOperations:100,aiMonthlyBudgetUsd:0,aiUnitBudgetUsd:1,cloudflareWarningUsd:0,cloudflareStopUsd:0,cloudflareObservedUsd:0,cloudflareObservedMonth:new Date().toISOString().slice(0,7),allowOverages:true};
const budgetLabels:Record<string,string>={memberLimit:'Member limit',memberStorageBytes:'Storage per member (bytes)',totalStorageBytes:'Total storage (bytes)',aiConcurrency:'Simultaneous AI actions',aiDailyOperations:'AI actions per day',aiMonthlyBudgetUsd:'Monthly AI budget (US$)',aiUnitBudgetUsd:'Estimated hold per unit, including retries (US$)',cloudflareWarningUsd:'Cloudflare warning amount (US$)',cloudflareStopUsd:'Cloudflare stop amount (US$)',cloudflareObservedUsd:'Measured Cloudflare cost this month (US$)',cloudflareObservedMonth:'Measurement month (YYYY-MM)',allowOverages:'Allow overages within the configured stop amount'};
export function AdminPage(){
 const [data,setData]=useState<Overview|null>(null),[config,setConfig]=useState<Record<string,unknown>>(defaults),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
 const [userId,setUserId]=useState(''),[credits,setCredits]=useState(1),[action,setAction]=useState('scan_single'),[email,setEmail]=useState('');
 async function load(){const next=await apiJson<Overview>('/api/admin/overview');setData(next);if(next.settings)setConfig(next.settings)}
 useEffect(()=>{void load().catch(e=>setMessage(e.message))},[]);
 async function run(fn:()=>Promise<unknown>){setBusy(true);setMessage('');try{const result=await fn();setMessage(typeof result==='string'?result:'Saved');await load()}catch(e){setMessage((e as Error).message)}finally{setBusy(false)}}
 async function rollout(kind:string){let complete=false;while(!complete){const result=await apiJson<{complete:boolean;processed:number}>(`/api/admin/rollout/${kind}`,'POST',{});complete=result.complete;setMessage(`${kind}: processed ${result.processed}${complete?' — complete':''}`)}return `${kind} complete`}
 return <section className="account-page"><h1>Owner controls</h1>{message&&<p role="status">{message}</p>}{data&&<p>Estimated provider AI cost: US${data.aiCost.usd.toFixed(2)} · {data.aiCost.searches} searches. Estimates can lag provider billing.</p>}
 {Number(config.cloudflareObservedUsd)>=Number(config.cloudflareWarningUsd)&&Number(config.cloudflareWarningUsd)>0&&<p role='alert'>Cloudflare spending has reached your warning amount. Review current usage before more AI work.</p>} <fieldset disabled={busy}><legend>Pilot budgets</legend><p>Set your budget amounts before admitting members. Storage is in bytes and budgets are in US dollars.</p>{Object.entries(config).map(([key,value])=><label key={key}>{budgetLabels[key]??key}{typeof value==='boolean'?<input type="checkbox" checked={value} onChange={e=>setConfig({...config,[key]:e.target.checked})}/>:<input type={typeof value==='number'?'number':'text'} value={String(value)} onChange={e=>setConfig({...config,[key]:typeof value==='number'?Number(e.target.value):e.target.value})}/>}</label>)}<button onClick={()=>void run(()=>apiJson('/api/admin/settings','PUT',config))}>Save budgets</button></fieldset>
 <fieldset disabled={busy}><legend>Credit prices</legend><select aria-label="AI action" value={action} onChange={e=>setAction(e.target.value)}>{data?.actions.map(a=><option key={a} value={a}>{a.replaceAll('_',' ')}</option>)}</select><label>Credits<input type="number" min="1" value={credits} onChange={e=>setCredits(Number(e.target.value))}/></label><button onClick={()=>void run(()=>apiJson('/api/admin/prices','POST',{action,credits}))}>Set new price</button><ul>{data?.prices.slice(0,10).map(p=><li key={p.id}>{p.action}: {p.credits}</li>)}</ul></fieldset>
 <fieldset disabled={busy}><legend>Members and grants</legend><select aria-label="Member" value={userId} onChange={e=>setUserId(e.target.value)}><option value="">Choose member</option>{data?.members.map(m=><option key={m.id} value={m.id}>{m.display_name} ({m.balance} credits)</option>)}</select><label>Credits to grant<input type="number" min="1" value={credits} onChange={e=>setCredits(Number(e.target.value))}/></label><button disabled={!userId} onClick={()=>void run(()=>apiJson('/api/admin/credits/grant','POST',{userId,credits,idempotencyKey:crypto.randomUUID(),reason:'Owner grant'}))}>Grant credits</button><ul>{data?.members.filter(m=>m.id!=='owner').map(m=><li key={m.id}>{m.email} — {m.status} <button onClick={()=>void run(()=>apiJson(`/api/admin/members/${m.id}`,'PATCH',{status:m.status==='active'?'suspended':'active'}))}>{m.status==='active'?'Suspend':'Restore'}</button></li>)}</ul></fieldset>
 <fieldset disabled={busy}><legend>Launch preparation</legend><button onClick={()=>void run(()=>rollout('storage'))}>Inventory R2 storage</button><button onClick={()=>void run(()=>rollout('research'))}>Index existing research</button><label>Invite email<input type="email" value={email} onChange={e=>setEmail(e.target.value)}/></label><button onClick={()=>void run(async()=>(await apiJson<{url:string}>('/api/admin/invitations','POST',{email})).url)}>Create member invitation</button></fieldset>
 {!!data?.reviewOperations.length&&<><h2>Operations needing reconciliation</h2><p>These reservations remain held because completion is uncertain. Reconcile provider status before releasing credits.</p><ul>{data.reviewOperations.map(op=><li key={op.id}>{op.id} — {op.path}</li>)}</ul></>}
 </section>;
}
