// Generated by scripts/build_grand_cru_climats.py; edit that script, not this file.
export type ClimatParcelFile={schemaVersion:1;parentFeatureId:string;inputs:{parcelSnapshotSha256:string};
 climats:Record<string,{name:string;parcels:Record<string,[areaM2:number,parcelPercent:number]>}>};

/** INAO climats inside a Grand Cru (Corton Les Bressandes, Chablis Les Clos), each mapped to the cru whose parcel rights it shares. */
export const climatParents:Readonly<Record<string,string>>={"inao-denom-2348":"inao-denom-549","inao-denom-2349":"inao-denom-549","inao-denom-2350":"inao-denom-549","inao-denom-2351":"inao-denom-549","inao-denom-2352":"inao-denom-549","inao-denom-2353":"inao-denom-549","inao-denom-2354":"inao-denom-549","inao-denom-2355":"inao-denom-549","inao-denom-2356":"inao-denom-549","inao-denom-2357":"inao-denom-549","inao-denom-2358":"inao-denom-549","inao-denom-2359":"inao-denom-549","inao-denom-2360":"inao-denom-549","inao-denom-2361":"inao-denom-549","inao-denom-2362":"inao-denom-549","inao-denom-2363":"inao-denom-549","inao-denom-2364":"inao-denom-549","inao-denom-2365":"inao-denom-549","inao-denom-2366":"inao-denom-549","inao-denom-2367":"inao-denom-549","inao-denom-2368":"inao-denom-549","inao-denom-2369":"inao-denom-549","inao-denom-2370":"inao-denom-549","inao-denom-2371":"inao-denom-549","inao-denom-440":"inao-denom-439","inao-denom-441":"inao-denom-439","inao-denom-442":"inao-denom-439","inao-denom-443":"inao-denom-439","inao-denom-444":"inao-denom-439","inao-denom-445":"inao-denom-439","inao-denom-446":"inao-denom-439"};

// One chunk per cru, loaded only when a climat's parcels are shown.
const loaders:Readonly<Record<string,()=>Promise<{default:unknown}>>>={
 'inao-denom-439':()=>import('./chablis-grand-cru.climats.json'),
 'inao-denom-549':()=>import('./corton.climats.json'),
};
export const loadClimatParcels=(parentFeatureId:string):Promise<ClimatParcelFile|null>=>
 loaders[parentFeatureId]?.().then(module=>module.default as ClimatParcelFile)??Promise.resolve(null);
