// Generated by scripts/build_grand_cru_app_registry.py.
import index0 from './clos-de-la-roche.named-plot-index.json';
import index1 from './clos-des-lambrays.named-plot-index.json';
import index2 from './clos-saint-denis.named-plot-index.json';
import index3 from './echezeaux.named-plot-index.json';
import index4 from './musigny.named-plot-index.json';
import index5 from './richebourg.named-plot-index.json';

export const namedPlotCrus=[
 {name:"Clos de la Roche",villageMaps:["morey-saint-denis"],index:index0,load:()=>import('./clos-de-la-roche.named-plots.json')},
 {name:"Clos des Lambrays",villageMaps:["morey-saint-denis"],index:index1,load:()=>import('./clos-des-lambrays.named-plots.json')},
 {name:"Clos Saint-Denis",villageMaps:["morey-saint-denis"],index:index2,load:()=>import('./clos-saint-denis.named-plots.json')},
 {name:"Échezeaux",villageMaps:["vosne-romanee"],index:index3,load:()=>import('./echezeaux.named-plots.json')},
 {name:"Musigny",villageMaps:["chambolle-musigny"],index:index4,load:()=>import('./musigny.named-plots.json')},
 {name:"Richebourg",villageMaps:["vosne-romanee"],index:index5,load:()=>import('./richebourg.named-plots.json')},
];
