// Generated by scripts/build_grand_cru_app_registry.py.
import index0 from './clos-des-lambrays.named-plot-index.json';
import index1 from './echezeaux.named-plot-index.json';
import index2 from './musigny.named-plot-index.json';
import index3 from './richebourg.named-plot-index.json';

export const namedPlotCrus=[
 {name:"Clos des Lambrays",villageMaps:["morey-saint-denis"],index:index0,load:()=>import('./clos-des-lambrays.named-plots.json')},
 {name:"Échezeaux",villageMaps:["vosne-romanee"],index:index1,load:()=>import('./echezeaux.named-plots.json')},
 {name:"Musigny",villageMaps:["chambolle-musigny"],index:index2,load:()=>import('./musigny.named-plots.json')},
 {name:"Richebourg",villageMaps:["vosne-romanee"],index:index3,load:()=>import('./richebourg.named-plots.json')},
];
