"""Parcels inside each official climat of a Grand Cru, from the committed parcel and village-map files.

Corton and Chablis Grand Cru are divided into INAO climats (Corton Les Bressandes, Les Clos), each its
own feature on the village maps but sharing the cru's parcel rights. For every app cru with climats this
measures each parcel's area inside each climat, so a climat's wine can show only its own parcels.

  python scripts/build_grand_cru_climats.py
  python scripts/build_grand_cru_climats.py --check

No downloads: the inputs are the hash-pinned parcel file and reviewed village maps already in the
repository. Areas are measured in Lambert-93, as in build_grand_cru_parcels.py. Requires
scripts/burgundy-map-requirements.txt.
"""
import argparse
import json

from pyproj import Transformer
from shapely.geometry import shape
from shapely.ops import transform

from grand_cru import (APP_DIR, _village_map, app_cru_slugs, bundle_village_maps, in_cru, load_cru, load_manifest,
                       parcel_asset, record_json, require, write_or_check)

# INAO climat outlines and the current cadastre are drawn separately, so a parcel wholly in one climat
# still grazes its neighbours. In Corton 73 contacts hold under 5% of the parcel's area in the cru, most
# under 1%, against 535 over 90%. A parcel really split between climats (Les Clos and Valmur) counts in both.
MINIMUM_CRU_SHARE = 0.05


def climat_features(cru, bundle):
    """The cru's climats on every village map it appears on; repeated copies must agree."""
    climats, digests = {}, {}
    for map_id in bundle_village_maps(bundle):
        if map_id not in cru['villageMaps']:
            continue
        _, canonical, digest = _village_map(map_id)
        digests[map_id] = digest
        for feature in json.loads(canonical)['features']:
            props = feature['properties']
            if props['kind'] != 'vineyard' or props.get('parentAppellation') != cru['name']:
                continue
            previous = climats.setdefault(feature['id'], feature)
            require(previous == feature, f'{feature["id"]} differs between village maps')
    return climats, digests


def build(cru, bundle, climats, digests):
    manifest = load_manifest(bundle)
    project = Transformer.from_crs(4326, 2154, always_xy=True).transform
    metric = {id: transform(project, shape(f['geometry'])) for id, f in climats.items()}
    result = {id: {'name': f['properties']['name'], 'parcels': {}} for id, f in sorted(climats.items())}
    excluded = 0
    minimum = bundle['parcels']['minimumOverlapM2']
    for feature in json.loads(parcel_asset(manifest))['features']:
        props = feature['properties']
        if not in_cru(feature, cru['parentFeatureId']):
            continue
        in_parent = next(o for o in props['overlaps'] if o['parentFeatureId'] == cru['parentFeatureId'])['areaM2']
        geometry = transform(project, shape(feature['geometry']))
        for climat_id, climat in metric.items():
            # As for the cru itself, only the communes INAO lists for the climat hold its parcels.
            if props['commune'] not in climats[climat_id]['properties']['communes']:
                continue
            area = geometry.intersection(climat).area
            if area <= minimum:
                continue
            if area < MINIMUM_CRU_SHARE * in_parent:
                excluded += 1
                continue
            result[climat_id]['parcels'][props['id']] = [round(area, 4), round(100 * area / geometry.area, 4)]
    for climat_id, entry in result.items():
        require(entry['parcels'], f'{climat_id} ({entry["name"]}) holds no mapped parcel')
    return {
        'schemaVersion': 1, 'parentFeatureId': cru['parentFeatureId'],
        'note': 'Area of each parcel inside each INAO climat of the cru, and its share of the parcel. Not ownership.',
        'inputs': {'parcelSnapshotSha256': manifest['sha256'], 'villageMapSha256': digests},
        'minimumCruShare': MINIMUM_CRU_SHARE, 'excludedEdgeContacts': excluded,
        'climats': result,
    }


def module(files):
    parents = {climat: cru['parentFeatureId'] for cru, data in files for climat in data['climats']}
    loaders = ''.join(f" '{cru['parentFeatureId']}':()=>import('./{cru['slug']}.climats.json'),\n" for cru, _ in files)
    return ('// Generated by scripts/build_grand_cru_climats.py; edit that script, not this file.\n'
            'export type ClimatParcelFile={schemaVersion:1;parentFeatureId:string;inputs:{parcelSnapshotSha256:string};\n'
            ' climats:Record<string,{name:string;parcels:Record<string,[areaM2:number,parcelPercent:number]>}>};\n\n'
            '/** INAO climats inside a Grand Cru (Corton Les Bressandes, Chablis Les Clos), each mapped to the cru whose parcel rights it shares. */\n'
            'export const climatParents:Readonly<Record<string,string>>='
            + json.dumps(dict(sorted(parents.items())), ensure_ascii=False, separators=(',', ':')) + ';\n\n'
            '// One chunk per cru, loaded only when a climat\'s parcels are shown.\n'
            'const loaders:Readonly<Record<string,()=>Promise<{default:unknown}>>>={\n' + loaders + '};\n'
            'export const loadClimatParcels=(parentFeatureId:string):Promise<ClimatParcelFile|null>=>\n'
            ' loaders[parentFeatureId]?.().then(module=>module.default as ClimatParcelFile)??Promise.resolve(null);\n')


def generate(check=False):
    files = []
    for slug in app_cru_slugs():
        cru, bundle = load_cru(slug)
        climats, digests = climat_features(cru, bundle)
        if not climats:
            continue
        data = build(cru, bundle, climats, digests)
        write_or_check(APP_DIR / f'{slug}.climats.json', record_json(data), check)
        files.append((cru, data))
        print(json.dumps({'cru': slug, 'climats': len(data['climats']), 'excludedEdgeContacts': data['excludedEdgeContacts'],
                          'parcels': {c['name']: len(c['parcels']) for c in data['climats'].values()}}, ensure_ascii=False))
    write_or_check(APP_DIR / 'climats.ts', module(files), check)


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument('--check', action='store_true')
    generate(parser.parse_args().check)
