/**
 * Emit the D1 migration that re-slots region and appellation on existing wines.
 *
 * Migrations are SQL only, so the resolver cannot run inside one. Instead the
 * tree is written out as a temporary lookup table of spelling -> depth, region,
 * appellation, and a single UPDATE picks, for each wine, the deepest place named
 * by either of its two columns. That is the same rule the runtime resolver
 * applies, so "California + Oakville" and "Napa Valley + Oakville" both settle on
 * Napa Valley / Oakville. Generated from the same hierarchy the resolver uses,
 * so the two cannot drift.
 *
 * Usage: npx vite-node scripts/generate_place_backfill.ts > src/lib/db/migrations/0032_place_hierarchy.sql
 */
import { PLACES,type PlaceNode } from '../src/lib/places/hierarchy';
import { ancestry,resolvePlace } from '../src/lib/places/resolve';

const TIER_DEPTH={country:0,area:1,region:2,subregion:3,appellation:4} as const;

const quote=(value:string|null)=>value==null?'NULL':`'${value.replace(/'/g,"''")}'`;

/**
 * SQLite has no accent folding, so a match is an explicit list of the literal
 * spellings a row could hold rather than a normalising expression.
 */
function spellings(place:PlaceNode){
  const forms=new Set<string>();
  for(const value of [place.name,...place.aliases]){
    for(const form of [value,value.normalize('NFD').replace(/[\u0300-\u036f]/g,'')]){
      forms.add(form);
      forms.add(form.replace(/’/g,"'"));
      forms.add(form.replace(/-/g,' '));
    }
  }
  return [...forms].filter(Boolean);
}

const header=[
  '-- Generated by scripts/generate_place_backfill.ts. Do not edit by hand.',
  '--',
  '-- region and appellation were filled by whichever slot recognition happened to',
  '-- pick. Old World labels were stable; AVAs nest three or four deep, so the same',
  '-- wine arrived as Napa Valley/Oakville one day and California/Napa Valley the',
  '-- next - splitting region counts in the Passport, and forking cuvee identity',
  '-- because the appellation is folded into the cuvee signature.',
  '--',
  '-- recognized_region and recognized_appellation keep what was there before this',
  '-- ran, so a wrong entry in the place tree stays recoverable and the disagreement',
  '-- rate between the model and the tree can be measured later.',
  '--',
  '-- An appellation the tree does not carry is left exactly as recorded rather',
  '-- than cleared. A value that starts with a known appellation is read as that',
  '-- appellation, so "Vosne-Romanee 1er Cru Les Suchots", "Vosne-Romanee Les',
  '-- Suchots" and "Vosne Romanee Suchots" all settle on Vosne-Romanee, the same',
  '-- way the runtime resolver reads them. Only a place below the region tier can',
  '-- be reached this way, so "Bourgogne Hautes Cotes de Nuits" is not swallowed.',
  '',
  'ALTER TABLE wines ADD COLUMN recognized_region TEXT;',
  'ALTER TABLE wines ADD COLUMN recognized_appellation TEXT;',
  'ALTER TABLE wines ADD COLUMN classification TEXT;',
  '',
  "UPDATE wines SET recognized_region=region WHERE recognized_region IS NULL AND trim(COALESCE(region,''))<>'';",
  "UPDATE wines SET recognized_appellation=appellation WHERE recognized_appellation IS NULL AND trim(COALESCE(appellation,''))<>'';",
  ''
];

type Row={spelling:string;depth:number;region:string|null;appellation:string|null;country:string|null};

const rows=new Map<string,Row>();
for(const place of PLACES){
  const resolved=resolvePlace({country:null,region:place.name,appellation:null});
  if(resolved.placeId!==place.id)continue;
  const country=ancestry(place).find(step=>step.tier==='country')?.name??null;
  const depth=TIER_DEPTH[place.tier];
  for(const spelling of spellings(place)){
    // An ambiguous spelling keeps the shallower reading: guessing the deeper one
    // would invent precision the label never carried.
    const existing=rows.get(spelling);
    if(existing&&existing.depth<=depth)continue;
    rows.set(spelling,{spelling,depth,region:resolved.region,appellation:resolved.appellation,country});
  }
}

// Bare cru forms, in a second pass so that a spelling which is a node in its own
// right - "Saint-Emilion Grand Cru", "Chablis Grand Cru" - always wins over the
// same text generated as a suffix of its parent village.
for(const place of PLACES){
  // A node that already names a cru takes no suffix: the resolver reads the
  // first marker, so the doubled form would not agree with it.
  if(place.tier!=='appellation'||/\b(?:premier|1er|grand)\s+cru\b/i.test(place.name))continue;
  const resolved=resolvePlace({country:null,region:place.name,appellation:null});
  if(resolved.placeId!==place.id)continue;
  const country=ancestry(place).find(step=>step.tier==='country')?.name??null;
  for(const suffix of [' Premier Cru',' 1er Cru',' Grand Cru']){
    for(const base of spellings(place)){
      const spelling=`${base}${suffix}`;
      if(rows.has(spelling))continue;
      rows.set(spelling,{spelling,depth:TIER_DEPTH[place.tier],region:resolved.region,appellation:resolved.appellation,country});
    }
  }
}

// Appellations the tree marks as crus in their own right, and as villages.
const grandCruNames=PLACES.filter(place=>place.classification==='grand_cru').map(place=>quote(place.name));
const villageNames=PLACES.filter(place=>place.classification==='village').map(place=>quote(place.name));
const grandCruStatements=grandCruNames.length?[
  "UPDATE wines SET classification='grand_cru'",
  `  WHERE classification IS NULL AND appellation IN (${grandCruNames.join(',')});`
]:[];

const values=[...rows.values()].sort((a,b)=>a.spelling.localeCompare(b.spelling))
  .map(row=>`(${quote(row.spelling)},${row.depth},${quote(row.region)},${quote(row.appellation)},${quote(row.country)})`);

const chunks:string[]=[];
for(let index=0;index<values.length;index+=120){
  chunks.push(`INSERT INTO place_backfill_map(spelling,depth,region,appellation,country) VALUES\n  ${values.slice(index,index+120).join(',\n  ')};`);
}

// The deepest place named by either column wins, matching resolvePlace.
const deepest=(column:string)=>`(SELECT p.${column} FROM place_backfill_map p
    WHERE p.spelling IN (trim(COALESCE(wines.region,'')),trim(COALESCE(wines.appellation,'')))
    ORDER BY p.depth DESC LIMIT 1)`;

const prefixMatch=`(SELECT p.appellation FROM place_backfill_map p
      WHERE p.depth>2 AND length(p.spelling)<length(trim(COALESCE(wines.appellation,'')))
        AND substr(trim(COALESCE(wines.appellation,'')),1,length(p.spelling)+1)=p.spelling||' '
      ORDER BY length(p.spelling) DESC LIMIT 1)`;

const appellationExpression=`COALESCE(
    (SELECT p.appellation FROM place_backfill_map p
      WHERE p.spelling=trim(COALESCE(wines.appellation,'')) AND p.depth>2),
    ${prefixMatch},
    CASE WHEN trim(COALESCE(wines.appellation,''))<>''
      AND NOT EXISTS (SELECT 1 FROM place_backfill_map p WHERE p.spelling=trim(wines.appellation))
      THEN wines.appellation END,
    ${deepest('appellation')})`;

process.stdout.write([...header,
  'CREATE TABLE place_backfill_map (',
  '  spelling TEXT PRIMARY KEY, depth INTEGER NOT NULL,',
  '  region TEXT, appellation TEXT, country TEXT',
  ');',
  '',
  ...chunks,
  '',
  'UPDATE wines SET',
  `  region=${deepest('region')},`,
  `  appellation=${appellationExpression},`,
  `  country=CASE WHEN trim(COALESCE(country,''))='' THEN ${deepest('country')} ELSE country END`,
  `WHERE EXISTS (SELECT 1 FROM place_backfill_map p`,
  `  WHERE p.spelling IN (trim(COALESCE(wines.region,'')),trim(COALESCE(wines.appellation,''))));`,
  '',
  '',
  '-- The cru tier is read from what was recorded before the place was normalised,',
  '-- because folding "Vosne-Romanee 1er Cru Les Suchots" into the village',
  '-- appellation is exactly what loses it. An appellation that is a place in its',
  '-- own right ("Saint-Emilion Grand Cru", "Chablis Grand Cru") is never read as',
  '-- a tier, so it is excluded by the map lookup.',
  "UPDATE wines SET classification='premier_cru'",
  "  WHERE classification IS NULL AND (lower(COALESCE(recognized_appellation,'')||' '||COALESCE(wine_name,''))",
  "    GLOB '*[0-9a-z ]1er cru*' OR lower(COALESCE(recognized_appellation,'')||' '||COALESCE(wine_name,'')) GLOB '1er cru*'",
  "    OR lower(COALESCE(recognized_appellation,'')||' '||COALESCE(wine_name,'')) LIKE '%premier cru%');",
  '',
  "UPDATE wines SET classification='grand_cru'",
  "  WHERE classification IS NULL",
  "    AND lower(COALESCE(recognized_appellation,'')||' '||COALESCE(wine_name,'')) LIKE '%grand cru%'",
  '    AND NOT EXISTS (SELECT 1 FROM place_backfill_map p WHERE p.spelling=trim(COALESCE(wines.recognized_appellation,\'\')));',
  '',
  ...grandCruStatements,
  '',
  "UPDATE wines SET classification='village'",
  '  WHERE classification IS NULL AND appellation IS NOT NULL',
  '    AND trim(COALESCE(recognized_appellation,\'\'))=trim(COALESCE(appellation,\'\'))',
  `    AND appellation IN (${villageNames.join(',')});`,
  '',
  'DROP TABLE place_backfill_map;',
  '',
  `-- ${rows.size} spellings across ${PLACES.length} tree nodes.`,''].join('\n'));
