import type { VillageMapCatalogue } from './burgundyVillageMap';

const loaders=new Map<string,()=>Promise<{default:VillageMapCatalogue}>>([
 ['bourgogne-cote-dor',()=>import('./bourgogne-cote-dorMapCatalogue.json')],
 ['bourgogne-hautes-cotes-de-nuits',()=>import('./bourgogne-hautes-cotes-de-nuitsMapCatalogue.json')],
 ['bourgogne-hautes-cotes-de-beaune',()=>import('./bourgogne-hautes-cotes-de-beauneMapCatalogue.json')],
 ['bourgogne-cote-chalonnaise',()=>import('./bourgogne-cote-chalonnaiseMapCatalogue.json')],
 ['bourgogne-cotes-du-couchois',()=>import('./bourgogne-cotes-du-couchoisMapCatalogue.json')],
 ['bourgogne-cotes-dauxerre',()=>import('./bourgogne-cotes-dauxerreMapCatalogue.json')],
 ['bourgogne-chitry',()=>import('./bourgogne-chitryMapCatalogue.json')],
 ['bourgogne-coulanges-la-vineuse',()=>import('./bourgogne-coulanges-la-vineuseMapCatalogue.json')],
 ['bourgogne-epineuil',()=>import('./bourgogne-epineuilMapCatalogue.json')],
 ['bourgogne-cote-saint-jacques',()=>import('./bourgogne-cote-saint-jacquesMapCatalogue.json')],
 ['bourgogne-tonnerre',()=>import('./bourgogne-tonnerreMapCatalogue.json')],
 ['bourgogne-la-chapelle-notre-dame',()=>import('./bourgogne-la-chapelle-notre-dameMapCatalogue.json')],
 ['bourgogne-le-chapitre',()=>import('./bourgogne-le-chapitreMapCatalogue.json')],
 ['bourgogne-montrecul',()=>import('./bourgogne-montreculMapCatalogue.json')],
 ['macon-charnay-les-macon',()=>import('./macon-charnay-les-maconMapCatalogue.json')],
 ['macon-davaye',()=>import('./macon-davayeMapCatalogue.json')],
 ['macon-fuisse',()=>import('./macon-fuisseMapCatalogue.json')],
 ['macon-loche',()=>import('./macon-locheMapCatalogue.json')],
 ['macon-solutre-pouilly',()=>import('./macon-solutre-pouillyMapCatalogue.json')],
 ['macon-vergisson',()=>import('./macon-vergissonMapCatalogue.json')],
 ['macon-vinzelles',()=>import('./macon-vinzellesMapCatalogue.json')],
 ['macon-bussieres',()=>import('./macon-bussieresMapCatalogue.json')],
 ['macon-chaintre',()=>import('./macon-chaintreMapCatalogue.json')],
 ['macon-la-roche-vineuse',()=>import('./macon-la-roche-vineuseMapCatalogue.json')],
 ['macon-milly-lamartine',()=>import('./macon-milly-lamartineMapCatalogue.json')],
 ['macon-pierreclos',()=>import('./macon-pierreclosMapCatalogue.json')],
 ['macon-prisse',()=>import('./macon-prisseMapCatalogue.json')],
 ['macon-serrieres',()=>import('./macon-serrieresMapCatalogue.json')],
 ['gevrey-chambertin',()=>import('./burgundyVillageMapCatalogue.json')],
 ['morey-saint-denis',()=>import('./moreyVillageMapCatalogue.json')],
 ['chambolle-musigny',()=>import('./chambolleVillageMapCatalogue.json')],
 ['vosne-romanee',()=>import('./vosneVillageMapCatalogue.json')],
 ['fixin',()=>import('./fixinVillageMapCatalogue.json')],
 ['vougeot',()=>import('./vougeotVillageMapCatalogue.json')],
 ['nuits-saint-georges',()=>import('./nuitsVillageMapCatalogue.json')],
 ['marsannay',()=>import('./marsannayVillageMapCatalogue.json')],
 ['cote-de-nuits-villages',()=>import('./coteNuitsVillageMapCatalogue.json')],
 ['meursault',()=>import('./meursaultVillageMapCatalogue.json')],
 ['puligny-montrachet',()=>import('./pulignyVillageMapCatalogue.json')],
 ['chassagne-montrachet',()=>import('./chassagneVillageMapCatalogue.json')],
 ['saint-aubin',()=>import('./saintAubinVillageMapCatalogue.json')],
 ['blagny',()=>import('./blagnyVillageMapCatalogue.json')],
 ['aloxe-corton',()=>import('./aloxeVillageMapCatalogue.json')],
 ['pernand-vergelesses',()=>import('./pernandVillageMapCatalogue.json')],
 ['ladoix',()=>import('./ladoixVillageMapCatalogue.json')],
 ['beaune',()=>import('./beauneVillageMapCatalogue.json')],
 ['pommard',()=>import('./pommardVillageMapCatalogue.json')],
 ['volnay',()=>import('./volnayVillageMapCatalogue.json')],
 ['savigny-les-beaune',()=>import('./savignyVillageMapCatalogue.json')],
 ['chorey-les-beaune',()=>import('./choreyVillageMapCatalogue.json')],
 ['auxey-duresses',()=>import('./auxeyVillageMapCatalogue.json')],
 ['monthelie',()=>import('./monthelieVillageMapCatalogue.json')],
 ['saint-romain',()=>import('./saintRomainVillageMapCatalogue.json')],
 ['santenay',()=>import('./santenayVillageMapCatalogue.json')],
 ['maranges',()=>import('./marangesVillageMapCatalogue.json')],
 ['cote-de-beaune',()=>import('./coteBeauneVillageMapCatalogue.json')],
 ['cote-de-beaune-villages',()=>import('./coteBeauneVillagesMapCatalogue.json')],
 ['bouzeron',()=>import('./bouzeronVillageMapCatalogue.json')],
 ['rully',()=>import('./rullyVillageMapCatalogue.json')],
 ['mercurey',()=>import('./mercureyVillageMapCatalogue.json')],
 ['givry',()=>import('./givryVillageMapCatalogue.json')],
 ['montagny',()=>import('./montagnyVillageMapCatalogue.json')],
 ['pouilly-fuisse',()=>import('./pouillyFuisseVillageMapCatalogue.json')],
 ['pouilly-loche',()=>import('./pouillyLocheVillageMapCatalogue.json')],
 ['pouilly-vinzelles',()=>import('./pouillyVinzellesVillageMapCatalogue.json')],
 ['saint-veran',()=>import('./saintVeranVillageMapCatalogue.json')],
 ['vire-clesse',()=>import('./vireClesseVillageMapCatalogue.json')],
 ['chablis',()=>import('./chablisVillageMapCatalogue.json')],
 ['petit-chablis',()=>import('./petitChablisVillageMapCatalogue.json')],
 ['irancy',()=>import('./irancyVillageMapCatalogue.json')],
 ['saint-bris',()=>import('./saintBrisVillageMapCatalogue.json')],
 ['vezelay',()=>import('./vezelayVillageMapCatalogue.json')],
]);

export async function loadVillageMapCatalogue(villageId:string):Promise<VillageMapCatalogue>{
 const load=loaders.get(villageId);
 if(!load)throw new Error('Village map is unavailable');
 return (await load()).default;
}
