import { useEffect,useMemo,useState } from 'react';
import { Link,useParams } from 'react-router-dom';
import { getProducer,listProducers,mergeProducer,researchProducer,unlinkProducer,type LinkedProducer,type ProducerDetail,type ProducerSummary } from './api';
import { normalizeProducerAlias } from '../../lib/producers/entities';
import '../../producer.css';

const wineKey=(name:string)=>normalizeProducerAlias(name).replace(/\b(grand cru|premier cru|1er cru|village)\b/g,'').trim();

export function ProducerDetailPage(){
 const {id=''}=useParams(),[producer,setProducer]=useState<ProducerDetail>(),[available,setAvailable]=useState<ProducerSummary[]>([]),[selectedAlias,setSelectedAlias]=useState(''),[loading,setLoading]=useState(true),[error,setError]=useState(''),[notice,setNotice]=useState(''),[researching,setResearching]=useState(false),[merging,setMerging]=useState(false),[unlinking,setUnlinking]=useState('');
 async function reload(){const [detail,directory]=await Promise.all([getProducer(id),listProducers()]);setProducer(detail);setAvailable(directory.items.filter(x=>x.id!==id));setSelectedAlias('')}
 useEffect(()=>{reload().catch(e=>setError(e.message)).finally(()=>setLoading(false))},[id]);
 const tastedKeys=useMemo(()=>new Set((producer?.tastedWines??[]).map(w=>wineKey(w.wineName))),[producer]);
 const linkedByName=useMemo(()=>new Map((producer?.linkedProducers??[]).map(link=>[normalizeProducerAlias(link.name),link])),[producer]);
 async function runResearch(){if(!confirm('Research this producer’s home location and current wine range with Gemini 3.7 Flash and Google Search?'))return;setResearching(true);setError('');setNotice('');try{const updated=await researchProducer(id);setProducer(p=>p?{...p,...updated}:p)}catch(e){setError((e as Error).message)}finally{setResearching(false)}}
 async function addAlias(){const source=available.find(x=>x.id===selectedAlias);if(!producer||!source)return;const ok=confirm(`Link “${source.canonicalName}” to “${producer.canonicalName}”?\n\n${producer.canonicalName} will remain the canonical producer. All wines and aliases from ${source.canonicalName} will be linked here. If both names already have research, WineLog will keep the newest complete result active, combine sources, and preserve the previous research in history.`);if(!ok)return;setMerging(true);setError('');setNotice('');try{const result=await mergeProducer(id,source.id);await reload();setNotice(`${result.mergedName} is now linked as an alias of ${result.canonicalName}.`)}catch(e){setError((e as Error).message)}finally{setMerging(false)}}
 async function unlinkAlias(link:LinkedProducer){if(!producer)return;const ok=confirm(`Unlink “${link.name}” from “${producer.canonicalName}”?\n\nWineLog will recreate ${link.name} as a separate producer, move back the wines that belonged to it when it was linked, and restore its archived research. Research added to ${producer.canonicalName} after the link will stay with ${producer.canonicalName}.`);if(!ok)return;setUnlinking(link.mergeId);setError('');setNotice('');try{const result=await unlinkProducer(id,link.mergeId);await reload();setNotice(`${result.unlinkedName} has been restored as a separate producer.`)}catch(e){setError((e as Error).message)}finally{setUnlinking('')}}
 if(loading)return <p>Loading producer…</p>;if(!producer)return <p role="alert">{error||'Producer not found'}</p>;
 const location=[producer.homeLocality,producer.homeRegion,producer.homeCountry].filter(Boolean).join(', ');
 return <article className="producer-detail"><Link className="back-pill" to="/producers">← Producers</Link><header className="producer-header"><p className="eyebrow">PRODUCER</p><h1>{producer.canonicalName}</h1><p>{location||'Home location not researched yet'}</p>{producer.aliases.length>1&&<small>Known aliases: {producer.aliases.join(' · ')}</small>}</header>
  {error&&<p className="producer-error" role="alert">{error}</p>}{notice&&<p className="producer-notice" role="status">{notice}</p>}
  <section className="detail-section producer-identity"><p className="section-label">IDENTITY & ALIASES</p><h2>Known producer names</h2><div className="alias-chips">{producer.aliases.map(alias=>{const link=linkedByName.get(normalizeProducerAlias(alias));return <span className="alias-chip" key={alias}>{alias}{link&&<button type="button" disabled={unlinking===link.mergeId} onClick={()=>unlinkAlias(link)}>{unlinking===link.mergeId?'Unlinking…':'Unlink'}</button>}</span>})}</div><p className="producer-help">Add alias only links another producer name that already exists in your WineLog database. It does not accept free-text names or create a new identity. Linked producer identities can be unlinked again from here.</p>
   {available.length>0?<div className="alias-link-control"><select aria-label="Existing producer name to link" value={selectedAlias} onChange={e=>setSelectedAlias(e.target.value)}><option value="">Select an existing producer…</option>{available.map(item=><option key={item.id} value={item.id}>{item.canonicalName}</option>)}</select><button type="button" disabled={!selectedAlias||merging} onClick={addAlias}>{merging?'Linking…':'Add alias'}</button></div>:<small>No other producer names are available to link.</small>}
   {producer.researchHistoryCount>0&&<small>{producer.researchHistoryCount} prior research version{producer.researchHistoryCount===1?' is':'s are'} preserved in merge history.</small>}
  </section>
  <section className="detail-section"><div className="producer-section-title"><div><p className="section-label">PRODUCER RESEARCH</p><h2>Profile & range</h2></div><button type="button" disabled={researching} onClick={runResearch}>{researching?'Researching…':producer.researchedAt?'Refresh producer research':'Research producer'}</button></div>{producer.profile?<p className="producer-profile">{producer.profile}</p>:<p>Research this producer to establish its physical base and a sourced current/recent wine range. This is stored once at producer level and reused.</p>}
   {producer.catalog.length>0&&<div className="producer-catalog">{producer.catalog.map((wine,index)=>{const tasted=tastedKeys.has(wineKey(wine.name));return <div className="catalog-row" key={`${wine.name}-${index}`}><div><strong>{wine.name}</strong><span>{[wine.appellation,wine.classification,wine.style].filter(Boolean).join(' · ')}</span>{wine.notes&&<small>{wine.notes}</small>}</div>{tasted&&<span className="tasted-badge">Tasted</span>}</div>})}</div>}
   {producer.sources.length>0&&<div className="producer-sources"><strong>Sources</strong>{producer.sources.map(s=><a key={s.url} href={s.url} target="_blank" rel="noreferrer">{s.title}</a>)}</div>}{producer.researchedAt&&<small>Latest producer research: {producer.researchModel} · {new Date(producer.researchedAt).toLocaleDateString()}</small>}
  </section>
  <section className="detail-section"><p className="section-label">YOUR TASTINGS</p><h2>{producer.tastedWines.length} tasted wine{producer.tastedWines.length===1?'':'s'}</h2>{producer.tastedWines.length?<div className="producer-tasted">{producer.tastedWines.map(w=><Link to={`/wines/${w.id}`} className="tasted-row" key={w.id}><div><strong>{w.wineName}</strong><span>{[w.vintage??'NV',w.appellation,w.region].filter(Boolean).join(' · ')}</span></div><div>{w.rating!=null&&<strong>{w.rating}</strong>}{w.tastingDate&&<span>{w.tastingDate}</span>}</div></Link>)}</div>:<p>No tasting records linked to this producer yet.</p>}</section>
 </article>
}
